#ifndef GUIID_H
#define GUIID_H

enum GUI_ID {
    ID_BUTTON_QUIT,
    ID_BUTTON_START,
    ID_BUTTON_SETTINGS,
    ID_BUTTON_MENU,
    ID_BUTTON_TOGGLE_FULLSCREEN,
    ID_BUTTON_RESUME,
    ID_BUTTON_CONTROL_SETTINGS,
    ID_BUTTON_CONTROL_UP,
    ID_BUTTON_CONTROL_LEFT,
    ID_BUTTON_CONTROL_DOWN,
    ID_BUTTON_CONTROL_RIGHT,
    ID_BUTTON_CONTROL_CW_ROLL,
    ID_BUTTON_CONTROL_CCW_ROLL,
    ID_BUTTON_DEFAULT_CONTROLS,
    ID_COMBOBOX_RESOLUTION,
    ID_COMBOBOX_LANGUAGE,
    ID_CHECKBOX_VSYNC,
    ID_CHECKBOX_STENCILBUFFER,
    ID_SPINBOX_RENDER_DISTANCE,

    GUI_IDS_COUNT};

#endif // GUIID_H
