#ifndef UTIL_H_INCLUDED
#define UTIL_H_INCLUDED

#include <irrlicht/irrlicht.h>

using namespace irr;

// GUI IDs
enum { ID_BUTTON_QUIT,
    ID_BUTTON_START,
    ID_BUTTON_SETTINGS,
    ID_BUTTON_MENU,
    ID_BUTTON_TOGGLE_FULLSCREEN,
    ID_RESOLUTION_COMBOBOX,
    ID_COLORDEPTH_COMBOBOX,
    ID_LANGUAGE_COMBOBOX};

#endif // UTIL_H_INCLUDED
